version: "3"
services:
    grafana:
       image: grafana/grafana:master
       container_name: grafana
       restart: always
       ports:
         - "3000:3000"
       networks:
         - grafana-net
       volumes:
         - grafana-volume
    graphite:
        image: graphiteapp/graphite-statsd
        container_name: graphite
        restart: always
        networks:
          - grafana-net
        ports:
          - "2003:2003"
          - "2004:2004"
          - "8000:8000"
networks:
    grafana-net:

volumes:
  grafana-volume:
    external: true
